# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170406_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='frase',
            field=models.CharField(default='hola', max_length=150),
            preserve_default=False,
        ),
    ]
