# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170528_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='er', max_length='100'),
            preserve_default=False,
        ),
    ]
