# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_frase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='frase',
        ),
    ]
