# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('intro', models.TextField(max_length=1000)),
                ('content', models.TextField()),
                ('url_media', models.FileField(blank=True, null=True, upload_to=post.models.media_post_path)),
                ('publicate_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('1', 'BORRADOR'), ('2', 'PUBLICADO')], default='1', max_length=1)),
                ('type', models.CharField(choices=[('1', 'PÚBLICO'), ('2', 'PRIVADO')], default='1', max_length=1)),
                ('likes', models.IntegerField(default=0)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('modify_at', models.DateField(auto_now=True)),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(to='category.Category')),
                ('post_response', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
                ('user_mention', models.ManyToManyField(blank=True, related_name='user_mention', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
