# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 21:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentary',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('comentary', models.TextField(max_length=500)),
                ('likes', models.IntegerField(default=0)),
                ('disikes', models.IntegerField(default=0)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('modify_at', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resp_comentary', models.ManyToManyField(blank=True, related_name='_comentary_resp_comentary_+', to='comentary.Comentary')),
            ],
        ),
    ]
