# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 17:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentary',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('comentary', models.TextField(max_length=500)),
                ('likes', models.IntegerField(default=0)),
                ('disikes', models.IntegerField(default=0)),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('post', models.ManyToManyField(to='post.Post')),
                ('resp_comentary', models.ManyToManyField(blank=True, related_name='_comentary_resp_comentary_+', to='comentary.Comentary')),
            ],
        ),
    ]
