# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comentary', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentary',
            name='post',
            field=models.ManyToManyField(to='post.Post'),
        ),
        migrations.AddField(
            model_name='comentary',
            name='resp_comentary',
            field=models.ManyToManyField(blank=True, related_name='_comentary_resp_comentary_+', to='comentary.Comentary'),
        ),
    ]
