# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favorites', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='post',
            field=models.ManyToManyField(to='post.Post'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
