# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Underline',
            fields=[
                ('pun_id', models.AutoField(primary_key=True, serialize=False)),
                ('content_underline', models.CharField(max_length=100)),
                ('post', models.ManyToManyField(to='post.Post')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
