# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follower', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='create_at',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follower',
            name='modify_at',
            field=models.DateField(auto_now=True),
        ),
    ]
